coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0.5%
        if_ci_failed: success #success, failure, error, ignore

# fix me
# The unittests of the torchrpc module are tested by different runners and cannot be included
# in the test_unittest's coverage report. To keep CI happy, we don't count torchrpc related coverage.
ignore: 
  - /mnt/cache/wangguoteng/DI-engine/ding/framework/message_queue/torch_rpc.py
  - /mnt/cache/wangguoteng/DI-engine/ding/framework/message_queue/perfs/*
